<?php

namespace Nemundo\Package\Jquery\Event;

use Nemundo\Com\JavaScript\Code\AbstractJavaScriptCode;

class ChangeJqueryEvent extends AbstractJqueryEvent
{


    protected function loadContainer()
    {

        parent::loadContainer(); // TODO: Change the autogenerated stub
        $this->eventName = 'change';

    }

    /*
    public function __construct(AbstractJavaScriptCode $parentContainer = null)
    {

        parent::__construct($parentContainer);
        $this->eventName = 'change';

    }*/

}