<?php


namespace Nemundo\App\MySql\Page;


use Nemundo\Admin\Com\Table\AdminLabelValueTable;
use Nemundo\Com\Template\AbstractTemplateDocument;
use Nemundo\Core\TextFile\Reader\TextFileReader;
use Nemundo\Db\Provider\MySql\Information\MySqlVariable;
use Nemundo\Db\Reader\SqlReader;
use Nemundo\Html\Paragraph\Paragraph;

class SlowLogPage extends AbstractTemplateDocument
{

    public function getContent()
    {


        //$statement = new SqlStatement();
        //$statement->sql= 'SHOW VARIABLES LIKE "slow_query_log_file"';

        /*
        $query = new SqlReader();  // new MySqlQuery();  //new MySqlConnection();
        $query->sqlStatement->sql = 'SHOW VARIABLES LIKE "slow_query_log_file"';   //->queryRow($statement);
        $row = $query->getRow();
        $value = $row->getValue('Value');*/

        $table = new AdminLabelValueTable($this);
        $table->addLabelValue('Slow Log', (new MySqlVariable())->getValue('slow_query_log'));
        $table->addLabelValue('Slow Log File', (new MySqlVariable())->getValue('slow_query_log_file'));




        $filename = '/var/lib/mysql/web03-slow.log';
        $reader = new TextFileReader($filename);
        foreach ($reader->getData() as $line) {

            $p = new Paragraph($this);
            $p->content = $line;

        }


        return parent::getContent(); // TODO: Change the autogenerated stub

    }

}