<?php

namespace Nemundo\App\System\Com\Table;


use Nemundo\Admin\Com\Table\AdminLabelValueTable;
use Nemundo\Core\Date\Duration\TimeDuration;
use Nemundo\Core\System\PhpEnvironment;
use Nemundo\Core\Type\DateTime\DateTime;
use Nemundo\Db\Provider\MySql\Information\MySqlVersion;

class MySqlSystemTable extends AdminLabelValueTable
{

    public function getContent()
    {

        $this->addLabelValue('MySql Version', (new MySqlVersion())->getMySqlVersion());
        $this->addLabelValue('Up Time', (new TimeDuration((new MySqlVersion())->getUpTime()))->getText());


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}