<?php


namespace Nemundo\App\CssDesigner\Com\Table;


use Nemundo\Admin\Com\Table\AdminClickableTable;
use Nemundo\Admin\Com\Table\AdminTableHeader;
use Nemundo\Admin\Com\Table\Row\AdminClickableTableRow;
use Nemundo\App\CssDesigner\Data\Style\StyleReader;
use Nemundo\App\CssDesigner\Parameter\StyleParameter;
use Nemundo\Web\Site\Site;

class StyleTable extends AdminClickableTable
{

    public function getContent()
    {




        $reader=new StyleReader();
        $reader->model->loadStyleType();

        $header=new AdminTableHeader($this);
        $header->addText($reader->model->style->label);
        $header->addText($reader->model->styleType->label);


        foreach ($reader->getData() as $styleRow) {

            $row=new AdminClickableTableRow($this);
            $row->addText($styleRow->style);

            $site = new Site();
            $site->addParameter(new StyleParameter($styleRow->id));
            $row->addClickableSite($site);



        }

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}