<?php

namespace Nemundo\Html\Script;


use Nemundo\Html\Header\AbstractHeaderHtmlContainer;


class JavaScriptCode extends AbstractJavaScriptCode
{

    public function addCodeLine($line)
    {
        return parent::addCodeLine($line); // TODO: Change the autogenerated stub
    }


    // addLine
    // addHtml
    // addCode
   /* public function addCodeLine($line)
    {
        $this->addContent($line);
        return $this;
    }


    public function getContent()
    {

        $this->tagName = 'script';
        $this->addAttribute('type', 'text/javascript');

        return parent::getContent();

    }*/

}