<?php


namespace Nemundo\Content\App\Text\Content\Text;


use Nemundo\Content\Form\AbstractContentFormPart;
use Nemundo\Core\Random\RandomText;
use Nemundo\Package\Bootstrap\FormElement\BootstrapTextBox;

use Nemundo\Content\Form\AbstractContentForm;

class TextContentFormPart extends AbstractContentFormPart
{

    /**
     * @var AbstractTextContentType
     */
    public $contentType;

    /**
     * @var BootstrapTextBox
     */
    protected $text;


    protected function loadContainer()
    {
        parent::loadContainer(); // TODO: Change the autogenerated stub


        $this->text = new BootstrapTextBox($this);
        $this->text->label = 'Text';


    }


    public function getContent()
    {


        if ($this->contentType->getDataId() !==null) {

            $textRow = $this->contentType->getDataRow();
            $this->text->value=$textRow->text;

        }

        return parent::getContent(); // TODO: Change the autogenerated stub

    }


    public function saveData()
    {

        //$type = new TextContentType();
        $this->contentType->text =$this->text->getValue();
        $this->contentType->saveType();

    }


    /*
    protected function loadUpdateForm()
    {

        $textRow = $this->contentType->getDataRow();
        $this->text->value = $textRow->text;

    }


    protected function onSubmit()
    {

        $this->contentType->text = $this->text->getValue();
        $this->contentType->saveType();

    }*/

}