<?php


namespace Nemundo\Content\App\Widget\Com\Container;


use Nemundo\Admin\Com\Table\AdminTable;
use Nemundo\Com\TableBuilder\TableRow;
use Nemundo\Core\Date\CalendarReader;
use Nemundo\Core\Date\DayReader;
use Nemundo\Core\Date\Week\CalendarWeek;
use Nemundo\Core\Type\DateTime\Date;
use Nemundo\Html\Container\AbstractHtmlContainer;

class CalendarWeekContainer extends AbstractHtmlContainer
{

    public function getContent()
    {


        //$reader=new CalendarWeek()


        //$reader=new CalendarReader();  // new CalendarReader();

        $table=new AdminTable($this);

        $year=2017;

        $reader = new DayReader();
        $reader->dateFrom=(new Date())
            ->setDay(1)
            ->setMonth(1)
            ->setYear($year);
        $reader->dateTo=(new Date())
            ->setDay(31)
            ->setMonth(12)
            ->setYear($year);

        foreach ($reader->getData() as $date) {

            if ($date->getWeekdayNumber()==1) {
            $row=new TableRow($table);
            $row->addText($date->getWeekNumber());
            $row->addText($date->getLongFormatWithWeekday());
            }

        }





        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}