<?php

namespace Nemundo\App\Help\Com\ListBox;

use Nemundo\App\Help\Data\Project\ProjectReader;
use Nemundo\App\Help\Parameter\ProjectParameter;
use Nemundo\Package\Bootstrap\FormElement\BootstrapListBox;

class ProjectListBox extends BootstrapListBox
{

    protected function loadContainer()
    {

        parent::loadContainer(); // TODO: Change the autogenerated stub
        $this->name=(new ProjectParameter())->getParameterName();

    }

    public function getContent()
    {
        $this->label = 'Project';

        $reader=new ProjectReader();
        foreach ($reader->getData() as $projectRow) {
            $this->addItem($projectRow->id,$projectRow->project);
        }


        return parent::getContent();
    }
}