<?php

namespace Nemundo\Package\Bootstrap\Icon;


use Nemundo\Html\Header\Link\StylesheetLink;

class BootstrapIconStylesheetLink extends StylesheetLink
{

    public function getContent()
    {

        $this->href = 'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css';


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}