<?php


namespace Nemundo\App\ModelDesigner\Page;


use Nemundo\Admin\Com\Title\AdminTitle;
use Nemundo\App\ModelDesigner\Com\Breadcrumb\ModelDesignerBreadcrumb;
use Nemundo\App\ModelDesigner\Com\Table\ProjectTable;
use Nemundo\App\ModelDesigner\Template\ModelDesignerTemplate;

class ModelDesignerPage extends ModelDesignerTemplate
{

    public function getContent()
    {

        $breadcrumb = new ModelDesignerBreadcrumb($this);

        $title = new AdminTitle($this);
        $title->content = 'Project List';

        new ProjectTable($this);

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


}