version: "3.9"
services:

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: php_project
      MYSQL_USER: php_project
      MYSQL_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    ports:
      - 7070:80
    volumes:
      - web_data:/var/www/html/data
    depends_on:
      - db

volumes:
  web_data:
  db_data: