<?php

namespace Nemundo\Geo\Kml\Property;


use Nemundo\Core\Type\Geo\AbstractGeoCoordinateAltitude;
use Nemundo\Core\Type\Geo\GeoCoordinate;
use Nemundo\Core\Type\Geo\GeoCoordinateAltitude;
use Nemundo\Html\Container\AbstractTagContainer;

class Coordinates extends AbstractTagContainer
{

    /**
     * @var AbstractGeoCoordinateAltitude
     */
    public $coordinate;

    public function getContent()
    {

        $this->tagName = 'coordinates';

        $longitude = round($this->coordinate->longitude, 5);
        $latitude = round($this->coordinate->latitude, 5);

        if ($this->coordinate->isObjectOfClass(GeoCoordinate::class)) {
            $this->addContent($longitude . ',' . $latitude . PHP_EOL);
        }

        if ($this->coordinate->isObjectOfClass(GeoCoordinateAltitude::class)) {
            $this->addContent($longitude . ',' . $latitude. ',' . $this->coordinate->altitude . PHP_EOL);
        }


        //$this->coordinateText .= $longitude . ',' . $latitude . ',' . $coordinate->altitude . PHP_EOL;



        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}