<?php


namespace Nemundo\Content\App\Favorite\Content;


use Nemundo\Html\Paragraph\Paragraph;
use Nemundo\Content\Form\AbstractContentForm;

class FavoriteContentForm extends AbstractContentForm
{

    public function getContent()
    {

        $p=new Paragraph($this);
        $p->content='Zu den Favoriten hinzufügen';

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {

        $type=new FavoriteContentType();
        $type->parentId=$this->parentId;
        $type->saveType();

    }

}