<?php


namespace Nemundo\Content\App\Job\Com\Table;


use Nemundo\Admin\Com\Table\AdminTable;
use Nemundo\Admin\Com\Table\Row\AdminTableRow;
use Nemundo\Content\App\Job\Com\Form\JobRunForm;
use Nemundo\Content\App\Job\Data\Job\JobReader;

class JobTable extends AdminTable
{

    public function getContent()
    {

        $reader=new JobReader();
        $reader->model->loadContentType()->contentType->loadApplication();
        $reader->addOrder($reader->model->job);
        foreach ($reader->getData() as $jobRow) {

            $row=new AdminTableRow($this);
            $row->addText($jobRow->job);
            $row->addText($jobRow->contentType->application->application);

            $form=new JobRunForm($row);
            $form->job=$jobRow->getJob();


        }


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}