<?php

namespace Nemundo\Com\JavaScript\Event;


use Nemundo\Com\JavaScript\Code\AbstractJavaScriptCode;

class ContentLoadedEvent extends AbstractJavaScriptCode
{

public function addCodeLine($line)
{
    return parent::addCodeLine($line); // TODO: Change the autogenerated stub
}

    public function getContent()
    {

        $this->addPreLine('document.addEventListener("DOMContentLoaded", function(event) {');
        $this->addAfterLine('});');

        /*
        document.addEventListener("DOMContentLoaded", function(event) {
            //do work
        });*/

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


}