<?php


namespace Nemundo\Content\App\Dashboard\Com\Form;


use Nemundo\Content\App\Dashboard\Data\Dashboard\Dashboard;
use Nemundo\Content\App\Dashboard\Event\DashboardEvent;
use Nemundo\Content\Index\Tree\Type\AbstractContentType;
use Nemundo\Package\Bootstrap\Form\BootstrapForm;
use Nemundo\Content\App\Dashboard\Com\ListBox\DashboardListBox;
use Nemundo\Content\App\Dashboard\Data\UserDashboard\UserDashboard;
use Nemundo\Content\App\Dashboard\Type\DashboardContentTypeCollection;
use Nemundo\Content\Com\ListBox\ContentTypeCollectionListBox;
use Nemundo\User\Type\UserSessionType;

class DashboardSaveForm extends BootstrapForm
{

    /**
     * @var ContentTypeCollectionListBox
     */
    //private $listbox;


    /**
     * @var AbstractContentType
     */
    public $contentType;

    public function getContent()
    {

        //$this->listbox =new DashboardListBox($this);
        //$listbox->contentTypeCollection = new DashboardContentTypeCollection();
        //$listbox->searchMode = true;
        //$listbox->submitOnChange = true;

        $this->submitButton->label='Add Dashboard';

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {

        /*$data = new UserDashboard();
        $data->userId=(new UserSessionType())->userId;
        $data->dashboardId=$this->listbox->getValue();
        $data->save();*/



       //$this->contentType->addEvent(new DashboardEvent());
       //$this->contentType->saveType();


        $data = new Dashboard();  // new UserDashboard();
        //$data->userId=(new UserSessionType())->userId;
        $data->contentId=$this->contentType->getContentId();
        $data->save();


    }


}