<?php

namespace Nemundo\App\Application\Type\Collection;


use Nemundo\App\Application\Type\AbstractApplication;


class ApplicationCollection extends AbstractApplicationCollection
{

    protected function loadCollection()
    {
        // TODO: Implement loadCollection() method.
    }


    public function addApplication(AbstractApplication $application)
    {
        return parent::addApplication($application); // TODO: Change the autogenerated stub
    }

    public function getApplicationList()
    {
        return parent::getApplicationList(); // TODO: Change the autogenerated stub
    }

}