<?php


namespace Hackathon\Site;


use Hackathon\Data\Word\WordReader;
use Nemundo\Package\Bootstrap\Autocomplete\AbstractAutocompleteJsonSite;

class KeywordAutocompleteJsonSite extends AbstractAutocompleteJsonSite
{

    /**
     * @var KeywordAutocompleteJsonSite
     */
    public static $site;

    protected function loadSite()
    {

        $this->url='autocomplete-json';

        KeywordAutocompleteJsonSite::$site=$this;

        // TODO: Implement loadSite() method.
    }


    protected function loadAutocompleteJson()
    {


        $reader = new WordReader();
        //$reader->filter->andContains($reader->model->word, $this->getKeyword());
        $reader->filter->andContainsLeft($reader->model->word, $this->getKeyword());
        $reader->addOrder($reader->model->word);
        $reader->limit=10;
        foreach ($reader->getData() as $wordRow) {
            $this->addWord($wordRow->word);
        }



        // TODO: Implement loadAutocompleteJson() method.
    }


    public function loadContent()
    {



        parent::loadContent(); // TODO: Change the autogenerated stub
    }

}