<?php

namespace Hackathon\Com\ListBox;

use Hackathon\Data\NewsType\NewsTypeReader;
use Nemundo\Content\Parameter\ContentTypeParameter;
use Nemundo\Package\Bootstrap\FormElement\BootstrapListBox;

class NewsTypeListBox extends BootstrapListBox
{

    protected function loadContainer()
    {
        parent::loadContainer(); // TODO: Change the autogenerated stub

        $this->name = (new ContentTypeParameter())->getParameterName();

    }

    public function getContent()
    {
        $this->label = 'News Type';

        $reader = new NewsTypeReader();
        $reader->model->loadContentType();
        foreach ($reader->getData() as $newsTypeRow) {
            //$this->addItem($newsTypeRow->contentTypeId, $newsTypeRow->contentType->contentType);
            $this->addItem($newsTypeRow->id, $newsTypeRow->contentType->contentType);
        }


        return parent::getContent();
    }
}