<?php

namespace Nemundo\Content\App\File\Com\Container;


use Nemundo\Admin\Com\Table\AdminTable;
use Nemundo\Com\TableBuilder\TableRow;
use Nemundo\Content\App\File\Data\Image\ImageReader;
use Nemundo\Content\App\File\Data\ImageIndex\ImageIndexPaginationReader;
use Nemundo\Html\Container\AbstractHtmlContainer;
use Nemundo\Package\Bootstrap\Image\BootstrapResponsiveImage;
use Nemundo\Package\Bootstrap\Pagination\BootstrapPagination;

class ImageIndexContainer extends AbstractHtmlContainer
{

    public function getContent()
    {


        $table=new AdminTable($this);

        $reader=new ImageIndexPaginationReader();


        foreach ($reader->getData() as $imageRow) {


            $row=new TableRow($table);

            $img=new BootstrapResponsiveImage($row);
            $img->src=$imageRow->image->getImageUrl($reader->model->imageAutoSize200);

        }


        $pagination=new BootstrapPagination($this);
        $pagination->paginationReader=$reader;


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}