<?php


namespace Nemundo\Content\Com\Container;


use Nemundo\Admin\Com\Button\AdminSiteButton;
use Nemundo\Content\App\Explorer\Site\Json\JsonExportSite;
use Nemundo\Content\Parameter\ContentParameter;
use Nemundo\Content\Type\JsonContentTrait;
use Nemundo\Package\Bootstrap\FormElement\BootstrapLargeTextBox;

class JsonContentContainer extends AbstractContentTypeContainer
{

    public function getContent()
    {

        if ($this->contentType->isObjectOfTrait(JsonContentTrait::class)) {

            $text = new BootstrapLargeTextBox($this);
            $text->label = 'Json';
            $text->value = $this->contentType->getJson();

            $btn = new AdminSiteButton($this);
            $btn->site= clone(JsonExportSite::$site);
            $btn->site->addParameter(new ContentParameter($this->contentType->getContentId()));


        }

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


}