<?php


namespace Nemundo\App\ClassDesigner\Designer\ListBox;


use Nemundo\App\ClassDesigner\Builder\AbstractClassBuilderForm;

class ListBoxClassBuilderForm extends AbstractClassBuilderForm
{


    protected function loadContainer()
    {
        parent::loadContainer(); // TODO: Change the autogenerated stub
        $this->formTitle='ListBox';
    }

    /*
    public function getContent()
    {

        return parent::getContent(); // TODO: Change the autogenerated stub
    }*/


    protected function onSubmit()
    {


        $builder =new ListBoxClassBuilder();
        $builder->project = $this->project;
        $builder->className = $this->className->getValue();
        $builder->namespace = $this->app->namespace;
        $builder->buildClass();



    }


}