<?php

namespace Nemundo\App\ModelDesigner\Path;


use Nemundo\Project\Path\ProjectPath;

class ModelPath extends ProjectPath
{

    protected function loadPath()
    {
        parent::loadPath(); // TODO: Change the autogenerated stub
        $this->addPath('model');
    }

    /*
    public function __construct()
    {
        parent::__construct();
        $this->addPath('model');
        //$this->addPath('paranautik.json');
    }*/

}