<?php


namespace Nemundo\Srf\Content\Channel;


use Nemundo\Content\Type\AbstractContentType;


class ChannelType extends AbstractContentType
{

    //use TreeTypeTrait;


    protected function loadContentType()
    {

        $this->typeLabel='Channel';
        $this->typeId='423530a0-f045-43da-9848-ff1278d49475';
        $this->viewClassList[]=ChannelContentView::class;

        // TODO: Implement loadContentType() method.
    }


    /*
    public function saveType()
    {
      //  return parent::saveType(); // TODO: Change the autogenerated stub

        $this->saveContentIndex2();

    }*/


    public function getSubject()
    {
        return 'SRF';  // parent::getSubject(); // TODO: Change the autogenerated stub
    }

}