<?php

namespace Nemundo\Content\Index\Tree\Com\ListBox;


use Nemundo\Content\App\Explorer\Content\Container\ContainerContentType;
use Nemundo\Content\Index\Tree\Data\RestrictedContentType\RestrictedContentTypeReader;
use Nemundo\Content\Parameter\ContentTypeParameter;
use Nemundo\Content\Type\AbstractContentType;
use Nemundo\Package\Bootstrap\FormElement\BootstrapListBox;

class RestrictedContentTypeListBox extends BootstrapListBox
{

    /**
     * @var AbstractContentType
     */
    public $contentType;


    protected function loadContainer()
    {

        parent::loadContainer(); // TODO: Change the autogenerated stub
        $this->name = (new ContentTypeParameter())->getParameterName();

    }


    public function getContent()
    {

        $reader = new RestrictedContentTypeReader();
        $reader->model->loadRestrictedContentType();
        $reader->filter->andEqual($reader->model->contentTypeId, $this->contentType->typeId);  // (new ContainerContentType())->typeId);
        $reader->addOrder($reader->model->restrictedContentType->contentType);
        foreach ($reader->getData() as $restrictedContentTypeRow) {
            $this->addItem($restrictedContentTypeRow->restrictedContentTypeId, $restrictedContentTypeRow->restrictedContentType->contentType);
        }

        return parent::getContent();

    }

}