<?php

namespace Nemundo\Content\App\Translation\Content\TranslationText;

use Nemundo\App\Translation\Com\Container\TranslationFormContainer;
use Nemundo\App\Translation\Type\Source\TextSourceType;
use Nemundo\Content\Form\AbstractContentForm;

class TranslationTextContentForm extends AbstractContentForm
{
    /**
     * @var TranslationTextContentType
     */
    public $contentType;

    /**
     * @var TranslationTextContentFormPart
     */
    private $translation;



    protected function loadContainer()
    {
        parent::loadContainer(); // TODO: Change the autogenerated stub

        //$this->translation= new TranslationTextContentFormPart($this);
        //$this->translation->contentType=$this->contentType;

    }


    public function getContent()
    {


        $this->translation=$this->contentType->getFormPart($this);


        return parent::getContent();
    }


    protected function loadUpdateForm()
    {

        //$this->translation->source = $this->contentType->getDataRow()->sourceId;

    }


    public function onSubmit()
    {

    //    $this->contentType->text=$this->translation->getTextList();
    //    $this->contentType->saveType();

        //$this->translation->contentType=$this->contentType;
        $this->translation->saveData();

    }

}