<?php


namespace Nemundo\Srf\Reader\Show;


use Nemundo\Core\Base\DataSource\AbstractDataSource;
use Nemundo\Core\Http\Url\UrlBuilder;
use Nemundo\Srf\Config\BusinessUnit;
use Nemundo\Srf\Reader\Json\SrfJsonReader;


class RadioShowJsonReader extends AbstractDataSource
{

    public $businessUnit = BusinessUnit::SRF;

    //public $query;

    protected function loadData()
    {
        //$this->loadCharacter('a-z');

        $list = range('A', 'Z');
        //$list[] = '#';

        foreach ($list as $character) {
            $this->loadCharacter($character);
        }

    }

    protected function loadCharacter($character)
    {

        $url = new UrlBuilder('https://api.srgssr.ch/audiometadata/v2/radioshows/search');
        $url->addRequestValue('bu', $this->businessUnit);
        $url->addRequestValue('q', $character);
        $url->addRequestValue('pageSize', 100);


        $reader = new SrfJsonReader();
        $reader->url = $url->getUrl();

        foreach ($reader->getData()[0]['searchResultListShow'] as $item) {

            $showItem = new ShowItem();
            $showItem->id = $item['id'];
            $showItem->show = $item['title'];

            $this->addItem($showItem);

            /*
            [title] => Es geschah am… Geisterzug von Spiez
            [description] =>
                    [imageUrl] => https://ws.srf.ch/asset/image/audio/b240bb16-f049-4204-8ee3-d1b91c3e2a05/WEBVISUAL/1570697836.jpg
                    [imageTitle] => Es geschah am… Geisterzug von Spiez
            [id] => 5937341d-e9b2-4457-8b20-50ebb4abb1c6
            [vendor] => SRF
            [transmission] => RADIO
            [urn] => urn:srf:show:radio:5937341d-e9b2-4457-8b20-50ebb4abb1c6
            [audioCount] => 6
                    [videoCount] => 0*/


        }


    }


    /**
     * @return ShowItem[]
     */
    public function getData()
    {
        return parent::getData(); // TODO: Change the autogenerated stub
    }


}