<?php

namespace Nemundo\Content\App\Store\Type;


class LargeTextStoreType extends AbstractLargeTextStoreType
{


    public function setValue($value)
    {
        parent::setValue($value); // TODO: Change the autogenerated stub
    }


    protected function loadStore()
    {

    }

}