<?php


namespace Nemundo\Geo\Kml\Site;


use Nemundo\Package\FontAwesome\Site\AbstractIconSite;
use Nemundo\Web\Site\AbstractSiteTree;

abstract class AbstractKmlSite extends AbstractIconSite
{

    public function __construct(AbstractSiteTree $site = null)
    {
        $this->title='Kml';
        $this->url='kml';
        parent::__construct($site);

        if ($this->icon->icon == null) {
            $this->icon->icon = 'globe';
        }

    }


    protected function loadSite()
    {
        parent::loadSite(); // TODO: Change the autogenerated stub
    }


}