<?php


namespace Nemundo\Content\Form;


use Nemundo\Content\Data\Content\ContentReader;
use Nemundo\Package\Bootstrap\FormElement\BootstrapListBox;

class ContentFormPart extends AbstractContentFormPart
{

    /**
     * @var BootstrapListBox
     */
    private $content;

    protected function loadContainer()
    {
        parent::loadContainer(); // TODO: Change the autogenerated stub

        $this->content = new BootstrapListBox($this);
        $this->content->label = 'Content';
        $this->content->validation = true;



    }


    public function getContent()
    {

        $reader = new ContentReader();
        $reader->filter->andEqual($reader->model->contentTypeId, $this->contentType->typeId);
        $reader->addOrder($reader->model->subject);
        foreach ($reader->getData() as $contentCustomRow) {
            $this->content->addItem($contentCustomRow->id, $contentCustomRow->subject);
        }


        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    public function saveData()
    {


        return $this->content->getValue();

    }


}