<?php


namespace Nemundo\App\ModelDesigner\Type\Form;


use Nemundo\App\ModelDesigner\Site\Json\ModelTypeJsonSite;
use Nemundo\App\ModelDesigner\Type\VirtualExternalModelDesignerType;
use Nemundo\Com\Container\LibraryTrait;
use Nemundo\Core\Debug\Debug;
use Nemundo\Html\Paragraph\Paragraph;
use Nemundo\Package\Bootstrap\FormElement\BootstrapListBox;
use Nemundo\Package\NemundoJs\NemundoJsPackage;
use Nemundo\Web\WebConfig;

class VirtualExternalTypeFormPart extends ExternalTypeFormPart
{

    use LibraryTrait;

    /**
     * @var VirtualExternalModelDesignerType
     */
    public $type;

    /**
     * @var BootstrapListBox
     */
    private $modelType;


    protected function loadContainer()
    {

        parent::loadContainer();


        $this->addPackage(new NemundoJsPackage());
        $this->addJsUrl(WebConfig::$webUrl . '../lib/framework/package/admin/js/model_designer.js');

        //$p = new Paragraph($this);
        //$p->content='Model'.$this->type->model->tableName;

        //(new Debug())->write($this->type);



        $this->modelType = new BootstrapListBox($this);
        $this->modelType->emptyValueAsDefault = false;
        $this->modelType->label = 'External Type';
        $this->modelType->inputId = 'external_type';


        //$type = new BootstrapListBox($this);
        //$type->label = 'Type';


        //$p = new Paragraph($this);
        //$p->content = ModelTypeJsonSite::$site->getUrl();


        //  return parent::getContent(); // TODO: Change the autogenerated stub
    }


    public function getJson()
    {
        parent::getJson(); // TODO: Change the autogenerated stub

        $this->type->externalFieldName = $this->modelType->getValue();

    }


}