<?php


namespace Nemundo\Content\App\Stream\_Widget;


use Nemundo\Admin\Com\Widget\AdminWidget;
use Nemundo\Db\Sql\Order\SortOrder;
use Nemundo\Html\Block\Br;
use Nemundo\Html\Block\Hr;
use Nemundo\Content\App\Stream\Data\Stream\StreamReader;
use Nemundo\Content\App\Stream\Site\StreamSite;

class StreamWidget extends AdminWidget
{


    public function getContent()
    {


        $this->widgetTitle='Stream';
        $this->widgetSite=StreamSite::$site;


        $reader=new StreamReader();
        $reader->model->loadContent();
        $reader->model->content->loadContentType();
        $reader->addOrder($reader->model->id, SortOrder::DESCENDING);
        $reader->limit= 20;

        foreach ($reader->getData() as $streamRow) {

            $contentType= $streamRow->content->getContentType();
            $contentType->getDefaultView($this);

        }


        (new Br($this));





        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}