<?php


namespace Nemundo\Content\App\Listing\Com\Form;


use Nemundo\Content\App\Listing\Data\ListingValue\ListingValue;
use Nemundo\Package\Bootstrap\Form\BootstrapForm;
use Nemundo\Package\Bootstrap\FormElement\BootstrapTextBox;

class ListingValueForm extends BootstrapForm
{

    public $listingId;

    /**
     * @var BootstrapTextBox
     */
    private $value;

    public function getContent()
    {

        $this->value=new BootstrapTextBox($this);
        $this->value->label='Value';
        $this->value->validation=true;

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

    protected function onSubmit()
    {

        $data=new ListingValue();
        $data->listingId=$this->listingId;
        $data->value=$this->value->getValue();
        $data->save();

    }

}