<?php


namespace Nemundo\App\Linux\Reader;


class FindReader extends CommandReader
{

    public $path='/';

    //d or f
    public $type;

    protected function loadData()
    {


        // find /srv -maxdepth 1 -type d -printf "%f %TD\n" | sort -z


        //  | sort -z |
//        $this->command= 'find ' . $this->path . ' -maxdepth 1 -type '.$this->type.' -printf "%p %TD\n"';
        $this->command= 'find ' . $this->path . ' -maxdepth 1 -type '.$this->type.' -printf "%f %TD\n"';

        parent::loadData(); // TODO: Change the autogenerated stub
    }


}