<?php


namespace Nemundo\Srf\Com\Container;


use Nemundo\Html\Container\AbstractHtmlContainer;

class EpisodeContainer extends AbstractHtmlContainer
{

    public function getContent()
    {



        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}