<?php


namespace Nemundo\Model\Path;


use Nemundo\Core\Path\AbstractPath;
use Nemundo\Model\ModelConfig;

class RedirectDataPath extends AbstractPath  // Path
{

    protected function loadPath()
    {
        //parent::loadPath(); // TODO: Change the autogenerated stub
        $this->addPath(ModelConfig::$redirectDataPath);
    }


    /*
    public function __construct()
   {
       parent::__construct();
       $this->addPath(ModelConfig::$redirectDataPath);
   }*/

}