<?php


namespace Nemundo\App\CssDesigner\Com\Form;


use Nemundo\Admin\Com\Form\AbstractAdminEditForm;
use Nemundo\Package\Bootstrap\FormElement\BootstrapColorPicker;

class StylePropertyForm extends AbstractAdminEditForm
{

    public function getContent()
    {

        $color=new BootstrapColorPicker($form);
        $color->label='Background Color';

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}