<?php


namespace Nemundo\App\CssDesigner\Com\Form;


use Nemundo\Admin\Com\Form\AbstractAdminEditForm;
use Nemundo\App\CssDesigner\Com\ListBox\StyleTypeListBox;
use Nemundo\App\CssDesigner\Data\Style\Style;
use Nemundo\App\CssDesigner\Data\Style\StyleModel;
use Nemundo\App\CssDesigner\Data\Style\StyleReader;
use Nemundo\App\CssDesigner\Data\Style\StyleUpdate;
use Nemundo\Package\Bootstrap\Form\BootstrapForm;
use Nemundo\Package\Bootstrap\FormElement\BootstrapTextBox;

class StyleForm extends AbstractAdminEditForm
{

    /**
     * @var StyleTypeListBox
     */
    private $styleType;

    /**
     * @var BootstrapTextBox
     */
    private $style;


    public function getContent()
    {

        $model=new StyleModel();


        $this->styleType=new StyleTypeListBox($this);


        $this->style=new BootstrapTextBox($this);
        $this->style->label=$model->style->label;
        $this->style->validation=true;

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function loadUpdateForm()
    {
        // TODO: Implement loadUpdateForm() method.

        $styleRow = (new StyleReader())->getRowById($this->dataId);
        $this->styleType->value=$styleRow->styleTypeId;
        $this->style->value=$styleRow->style;

    }


    protected function onSave()
    {

        $data=new Style();
        $data->styleTypeId= 0;  // $this->styleType->getValue();
        $data->style=$this->style->getValue();
        $data->save();


    }


    protected function onUpdate()
    {

        $update=new StyleUpdate();
        $update->styleTypeId=$this->styleType->getValue();
        $update->style=$this->style->getValue();
        $update->updateById($this->dataId);

    }


}