<?php


namespace Nemundo\App\MySql\Com\Container;


use Nemundo\App\MySqlAdmin\Com\ListBox\MySqlTableListBox;
use Nemundo\Html\Container\AbstractContainer;
use Nemundo\Package\Bootstrap\Layout\BootstrapTwoColumnLayout;

class MySqlDatabaseContainer extends AbstractContainer
{

    public function getContent()
    {

        $layout=new BootstrapTwoColumnLayout($this);
        $layout->col1->columnWidth=2;
        $layout->col2->columnWidth=10;

        $list=new MySqlTableListBox($this);



        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}