<?php

namespace Nemundo\Content\App\PublicShare\Com;


use Nemundo\Admin\Com\Button\AdminCopyButton;
use Nemundo\Content\App\PublicShare\Parameter\PublicShareParameter;
use Nemundo\Content\App\PublicShare\Site\PublicShareSite;
use Nemundo\Html\Container\AbstractContainer;
use Nemundo\Package\Bootstrap\FormElement\BootstrapTextBox;
use Nemundo\Package\Bootstrap\Layout\Grid\BootstrapRow;

class PublicShareUrlContainer extends AbstractContainer
{

    public $shareId;


    public function getContent()
    {

        $row = new BootstrapRow($this);

        $site = clone(PublicShareSite::$site);
        $site->addParameter(new PublicShareParameter($this->shareId));


        $input = new BootstrapTextBox($row);
        $input->name = 'public_url_'.$this->shareId;
        $input->label = 'Public Url';
        $input->value = $site->getUrlWithDomain();
        $input->column = true;
        $input->columnSize = 12;

        $btn = new AdminCopyButton($row);
        $btn->copyId = $input->name;
        //$btn->col


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}