<?php


namespace Hackathon\Com;


use Hackathon\Data\Keyword\Keyword;
use Hackathon\Data\Topic\Topic;
use Hackathon\Parameter\TopicParameter;
use Hackathon\Site\HomeSite;
use Hackathon\Site\KeywordAutocompleteJsonSite;
use Nemundo\Package\Bootstrap\Autocomplete\BootstrapAutocompleteTextBox;
use Nemundo\Package\Bootstrap\Form\BootstrapForm;
use Nemundo\Package\Bootstrap\FormElement\BootstrapTextBox;

class KeywordForm extends BootstrapForm
{

    /**
     * @var BootstrapTextBox
     */
    private $keyword;

    public function getContent()
    {

        $this->keyword= new BootstrapAutocompleteTextBox($this);  // new BootstrapTextBox($this);
        $this->keyword->sourceSite=KeywordAutocompleteJsonSite::$site;
        $this->keyword->label='Keyword';
        $this->keyword->validation=true;

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {

        $data=new Keyword();
        $data->topicId=(new TopicParameter())->getValue();
        $data->keyword=$this->keyword->getValue();
        $data->save();


        /*
        $data=new Topic();
        $data->topic=$this->keyword->getValue();
        $id=$data->save();

        $this->redirectSite=HomeSite::$site;
        $this->redirectSite->addParameter(new TopicParameter($id));
*/
    }


}