<?php


namespace Hackathon\Com;


use Hackathon\Data\RssFeed\RssFeed;
use Hackathon\Index\NewsIndexBuilder;
use Nemundo\Package\Bootstrap\Form\BootstrapForm;
use Nemundo\Package\Bootstrap\FormElement\BootstrapTextBox;
use Nemundo\Rss\Reader\RssReader;

class RssFeedForm extends BootstrapForm
{

    /**
     * @var BootstrapTextBox
     */
    private $rssFeed;

    public function getContent()
    {

        $this->rssFeed = new BootstrapTextBox($this);
        $this->rssFeed->label = 'Rss Feed';
        $this->rssFeed->validation = true;


        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {


        $rssReader = new RssReader();
        $rssReader->feedUrl = $this->rssFeed->getValue();

        $data = new RssFeed();
        $data->rssUrl = $this->rssFeed->getValue();
        $data->feedTitle = $rssReader->getTitle();
        $data->save();


        foreach ($rssReader->getData() as $rssItem) {


            $builder = new NewsIndexBuilder();
            $builder->source=$rssReader->getTitle();
            $builder->sourceUniqueId=$this->rssFeed->getValue();

            $builder->title = $rssItem->title;
            $builder->text = '';  // $rssItem->description;
            $builder->url = $rssItem->url;
            $builder->createIndex();


        }


    }

}