<?php

namespace Nemundo\Content\App\Contact\Content\Phone;

use Nemundo\Content\Form\AbstractContentForm;
use Nemundo\Content\Form\AbstractContentFormPart;
use Nemundo\Core\Debug\Debug;
use Nemundo\Package\Bootstrap\FormElement\BootstrapTextBox;

class PhoneContentFormPart extends AbstractContentFormPart
{
    /**
     * @var PhoneContentType
     */
    public $contentType;

    /**
     * @var BootstrapTextBox
     */
    private $phone;


    protected function loadContainer()
    {
        parent::loadContainer(); // TODO: Change the autogenerated stub

        $this->phone = new BootstrapTextBox($this);
        $this->phone->label = 'Phone';

    }


    public function saveData()
    {

        $contentType= new PhoneContentType();
        $contentType->phone = $this->phone->getValue();
        $contentType->saveType();


        $dataId = $contentType->getDataId();

        //(new Debug())->write($dataId);
        //exit;

        return $dataId;

    }
}