<?php

namespace Nemundo\Content\App\Contact\Content\Phone;


use Nemundo\Admin\Com\Table\AdminTable;
use Nemundo\Com\TableBuilder\TableRow;
use Nemundo\Content\App\Contact\Data\Phone\PhoneReader;
use Nemundo\Content\View\AbstractContentListing;

class PhoneContentListing extends AbstractContentListing
{

    public function getContent()
    {


        $table=new AdminTable($this);

        $reader = new PhoneReader();
        foreach ($reader->getData() as $phoneRow) {

            $row=new TableRow($table);
            $row->addText($phoneRow->phone);

        }


        return parent::getContent(); // TODO: Change the autogenerated stub
    }


}