<?php


namespace Nemundo\App\ModelDesigner\Page\Type;


use Nemundo\App\ModelDesigner\Builder\TypeBuilder;
use Nemundo\App\ModelDesigner\Com\Breadcrumb\ModelDesignerBreadcrumb;
use Nemundo\App\ModelDesigner\Com\Form\TypeForm;
use Nemundo\App\ModelDesigner\Parameter\AppParameter;
use Nemundo\App\ModelDesigner\Parameter\FieldNameParameter;
use Nemundo\App\ModelDesigner\Parameter\ModelParameter;
use Nemundo\App\ModelDesigner\Parameter\ProjectParameter;
use Nemundo\App\ModelDesigner\Parameter\TypeParameter;
use Nemundo\App\ModelDesigner\Site\ModelSite;
use Nemundo\App\ModelDesigner\Site\Type\TypeEditSite;
use Nemundo\App\ModelDesigner\Site\Type\TypeNewSite;
use Nemundo\App\ModelDesigner\Template\ModelDesignerTemplate;
use Nemundo\Package\Bootstrap\Layout\BootstrapTwoColumnLayout;

class TypeEditPage extends ModelDesignerTemplate
{

    public function getContent()
    {

        $project = (new ProjectParameter())->getProject();
        $appJson = (new AppParameter())->getApp($project);
        $model = (new ModelParameter())->getModel($appJson);

        $breadcrumb = new ModelDesignerBreadcrumb($this);
        $breadcrumb->addProject($project);
        $breadcrumb->addApp($appJson);
        $breadcrumb->addModel($model);
        $breadcrumb->addActiveItem(TypeEditSite::$site->title);

        $layout = new BootstrapTwoColumnLayout($this);

        $form = new TypeForm($layout->col1);
        $form->project = $project;
        $form->appJson = $appJson;
        $form->model = $model;
        $form->type = (new TypeBuilder())->getTypeFromModel($model, (new FieldNameParameter())->getValue());
        $form->redirectSite = clone(ModelSite::$site);
        $form->redirectSite->addParameter(new ProjectParameter());
        $form->redirectSite->addParameter(new AppParameter());
        $form->redirectSite->addParameter(new ModelParameter());
        $form->updateMode = true;

        return parent::getContent(); // TODO: Change the autogenerated stub
        
    }

}