<?php

namespace Nemundo\Content\App\ImageTimeline\Content\ImageTimeline;

use Nemundo\Content\App\ImageTimeline\Content\ImageTimeline\View\ImageTimelineLatestContentView;
use Nemundo\Content\App\ImageTimeline\Content\ImageTimeline\View\ImageTimelineSliderContentView;
use Nemundo\Content\App\ImageTimeline\Data\ImageTimeline\ImageTimeline;
use Nemundo\Content\App\ImageTimeline\Data\ImageTimeline\ImageTimelineReader;
use Nemundo\Content\App\ImageTimeline\Data\ImageTimeline\ImageTimelineRow;
use Nemundo\Content\Type\AbstractContentType;

class ImageTimelineContentType extends AbstractImageTimelineContentType
{


    protected function loadContentType()
    {
        parent::loadContentType(); // TODO: Change the autogenerated stub



    }


}