<?php

namespace Nemundo\Content\App\ImageTimeline\Content\ImageTimeline;


use Nemundo\Admin\Com\Table\AdminClickableTable;
use Nemundo\Admin\Com\Table\AdminTableHeader;
use Nemundo\Admin\Com\Table\Row\AdminClickableTableRow;
use Nemundo\Content\App\ImageTimeline\Data\ImageTimeline\ImageTimelinePaginationReader;
use Nemundo\Content\View\AbstractContentListing;
use Nemundo\Package\Bootstrap\Pagination\BootstrapPagination;

class ImageTimelineContentListing extends AbstractContentListing
{

    public function getContent()
    {


        $table=new AdminClickableTable($this);



        $reader = new ImageTimelinePaginationReader();


        $header=new AdminTableHeader($table);
        $header->addText($reader->model->timeline->label);
        $header->addText($reader->model->crawling->label);


        foreach ($reader->getData() as $timelineRow) {

            $row=new AdminClickableTableRow($table);
            $row->addText($timelineRow->timeline);

            $row->addYesNo($timelineRow->crawling);

            $site = $this->getContentRedirectSite((new ImageTimelineContentType($timelineRow->id))->getContentId());
            $row->addClickableSite($site);

        }

        $pagination=new BootstrapPagination($this);
        $pagination->paginationReader=$reader;


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}