<?php

namespace Nemundo\Package\Bootstrap\Card;


use Nemundo\Html\Block\ContentDiv;
use Nemundo\Html\Block\Div;
use Nemundo\Html\Container\AbstractContainer;
use Nemundo\Html\Heading\H5;


class BootstrapCard extends Div
{


    public $header;


    /**
     * @var ContentDiv
     */
    protected $cardHeader;

    /**
     * @var Div
     */
    private $cardBody;

    protected function loadContainer()
    {
        parent::loadContainer(); // TODO: Change the autogenerated stub


        /*
        <div class="card-header">
    Featured
  </div>
        */


        $this->cardHeader= new Div(); // new ContentDiv();
        $this->cardHeader->addCssClass('card-header');


        $this->cardBody=new Div();
        $this->cardBody->addCssClass('card-body');

        parent::addContainer($this->cardHeader);
        parent::addContainer($this->cardBody);

    }

    public function getContent()
    {

        $this->addCssClass('card');
        //$this->addCssClass('card-block');


        if ($this->header !==null) {


            $h5=new H5($this->cardHeader);
            $h5->content = $this->header;

            //$this->cardHeader->content=$this->header;


        }


//        $this->cardHeader->conte

    //    <div class="card-body">


        return parent::getContent();
    }



    public function addContainer(AbstractContainer $container)
    {

        $this->cardBody->addContainer($container);

    }


}