<?php

namespace Nemundo\Admin\Com\Table\Sorting;


use Nemundo\Admin\Com\Table\Header\UpDownSortingHyperlink;


// AdminSortingCell
// AdminUpDownSorting
class AdminUpdDownSortingHyperlink extends UpDownSortingHyperlink
{




    public function getContent()
    {

        $this->hyperlink->addCssClass('text-decoration-none');
        $this->hyperlink->addCssClass('text-muted');

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}