<?php


namespace Nemundo\Geo\Kml\Element;


use Nemundo\Html\Container\AbstractTagContainer;

class OuterBoundary extends AbstractTagContainer
{

    public function getContent()
    {

        $this->tagName='outerBoundaryIs';

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}