<?php

namespace Nemundo\Geo\Kml\Element;


use Nemundo\Geo\Kml\Property\AltitudeMode\AltitudeMode;
use Nemundo\Geo\Kml\Property\AltitudeMode\AltitudeModeProperty;
use Nemundo\Geo\Kml\Property\Extrude;
use Nemundo\Html\Container\AbstractTagContainer;

class Polygon extends AbstractTagContainer
{


    public function getContent()
    {

        $this->tagName='Polygon';


        $extrude=new Extrude($this);
        $extrude->value= '1';

        $alt=new AltitudeModeProperty($this);
        $alt->value=AltitudeMode::CLAMP_TO_GROUND;





        /*
         *
         *  <extrude>1</extrude>

      <altitudeMode>relativeToGround</altitudeMode>

      <outerBoundaryIs>
         *
         *
        <Polygon>
        <extrude>1</extrude>
        <altitudeMode>relativeToGround</altitudeMode>
        <outerBoundaryIs>*/

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


}