<?php


namespace Nemundo\Package\Jquery\Com\Toggle;


use Nemundo\Package\Bootstrap\Button\BootstrapButton;

class ToggleButton extends BootstrapButton
{

    public $toggleId;


    public function getContent()
    {

        // $this->addCodeLine('$("#' . $this->codeId . '").toggle();');

        //form1

        //$this->addAttribute('onClick','alert();');
        $this->addAttribute('onClick','$(\'#' . $this->toggleId . '\').toggle();');



        return parent::getContent(); // TODO: Change the autogenerated stub

    }

}