<?php


namespace Nemundo\App\MySql\Widget;


use Nemundo\Admin\Com\Widget\AdminWidget;
use Nemundo\App\MySql\Com\Table\GlobalVariablesTable;

class GlobalVariableWidget extends AdminWidget
{

    public function getContent()
    {

        $this->widgetTitle='Global Variable';

        new GlobalVariablesTable($this);


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}