<?php


namespace Nemundo\Content\Com\Button;


use Nemundo\Admin\Com\Button\AdminSiteButton;
use Nemundo\Content\Parameter\ContentTypeParameter;
use Nemundo\Content\Index\Tree\Type\AbstractTreeContentType;
use Nemundo\Web\Site\Site;

class ContentTypeButton extends AdminSiteButton
{

    /**
     * @var AbstractTreeContentType
     */
    public $contentType;

    protected function loadContainer()
    {
        parent::loadContainer(); // TODO: Change the autogenerated stub

        $this->site=new Site();

    }

    public function getContent()
    {

        $this->site->title = $this->contentType->typeLabel;
        $this->site->addParameter(new ContentTypeParameter($this->contentType->typeId));

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}