<?php

namespace Nemundo\Content\App\Job\Com\ListBox;

use Nemundo\Content\App\Job\Data\Job\JobReader;
use Nemundo\Content\App\Job\Parameter\JobParameter;
use Nemundo\Package\Bootstrap\FormElement\BootstrapListBox;

class JobListBox extends BootstrapListBox
{

    protected function loadContainer()
    {
        parent::loadContainer(); // TODO: Change the autogenerated stub
        $this->name=(new JobParameter())->getParameterName();
    }

    public function getContent()
    {

        $this->label = 'Job';

        $reader = new JobReader();
        //$reader->model->loadApplication();
        $reader->addOrder($reader->model->job);
        foreach ($reader->getData() as $jobRow) {
            //$this->addItem($jobRow->id, $jobRow->job . ' (' . $jobRow->application->application . ')');
            $this->addItem($jobRow->id, $jobRow->job);
        }

        return parent::getContent();
    }
}