<?php

namespace Nemundo\Html\Container;


class TagContainer extends AbstractTagContainer
{


    /**
     * @var string
     */
    public $tagName;

    public function addContent($content)
    {
        return parent::addContent($content); // TODO: Change the autogenerated stub
    }


}