<?php

namespace Nemundo\Content\App\Translation\Content\Language;


use Nemundo\Admin\Com\Table\AdminTable;
use Nemundo\Com\TableBuilder\TableRow;
use Nemundo\Content\App\Translation\Data\Language\LanguageReader;
use Nemundo\Content\View\AbstractContentListing;

class LanguageContentListing extends AbstractContentListing
{

    public function getContent()
    {

        $table=new AdminTable($this);

        $reader=new LanguageReader();
        foreach ($reader->getData() as $languageRow) {

            $row=new TableRow($table);
            $row->addText($languageRow->code);
            $row->addText($languageRow->language);


        }

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}