<?php

namespace Nemundo\Package\Bootstrap\Navbar;


use Nemundo\Html\Listing\AbstractLi;

class BootstrapNavItemLi extends AbstractLi
{

    public function getContent()
    {
        $this->addCssClass('nav-item');
        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}