<?php

namespace Nemundo\Package\Bootstrap\Navbar;


use Nemundo\Com\Html\Hyperlink\SiteHyperlink;

class BootstrapNavLink extends SiteHyperlink
{

    public function getContent()
    {

        $this->addCssClass('nav-link');
        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}