<?php


namespace Nemundo\Html\Canvas;


use Nemundo\Html\Container\AbstractHtmlContainer;

class Canvas extends AbstractHtmlContainer
{

    public $width;

    public $height;

    protected function loadContainer()
    {
        parent::loadContainer();
        $this->tagName = 'canvas';
    }


    public function getContent()
    {

        $this->addAttribute('width',$this->width);
        $this->addAttribute('height',$this->height);


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}