<?php

namespace Nemundo\Com\JavaScript\Code;


class JavaScriptCode extends AbstractJavaScriptCode
{

    /*
    public function addPreLine($line)
    {
        parent::addPreLine($line); // TODO: Change the autogenerated stub
    }


    public function addAfterLine($line)
    {
        parent::addAfterLine($line); // TODO: Change the autogenerated stub
    }*/

    public function addCodeLine($line)
    {
        return parent::addCodeLine($line); // TODO: Change the autogenerated stub
    }

}