<?php

namespace Nemundo\Content\App\Favorite\Widget;


use Nemundo\Admin\Com\Widget\AdminWidget;
use Nemundo\Content\App\Favorite\Com\Container\FavoriteContainer;

class FavoriteWidget extends AdminWidget
{

    public function getContent()
    {

        $container=new FavoriteContainer($this);


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}