<?php


namespace Nemundo\Content\App\Calendar\Com\Container;


use Nemundo\Admin\Com\Table\AdminClickableTable;
use Nemundo\Com\TableBuilder\TableHeader;
use Nemundo\Content\App\Calendar\Parameter\CalendarParameter;
use Nemundo\Content\App\Calendar\Site\CalendarSite;
use Nemundo\Content\Com\Container\AbstractIndexContainer;
use Nemundo\Content\Index\Group\User\GroupMembership;
use Nemundo\Content\Parameter\ContentParameter;
use Nemundo\Core\Type\DateTime\Date;
use Nemundo\Html\Block\Div;
use Nemundo\Html\Container\AbstractHtmlContainer;
use Nemundo\Package\Bootstrap\Pagination\BootstrapPagination;
use Nemundo\Package\Bootstrap\Table\BootstrapClickableTableRow;
use Nemundo\Content\App\Calendar\Data\CalendarIndex\CalendarIndexPaginationReader;


// CalendarListContainer
class CalendarContentContainer extends AbstractIndexContainer  // AbstractHtmlContainer
{

    public function getContent()
    {

        $reader = new CalendarIndexPaginationReader();
        $reader->model->loadContent();
        $reader->model->content->loadContentType();
        $reader->model->loadGroup();

        $reader->filter->andEqualOrGreater($reader->model->date, (new Date())->setNow()->getIsoDate());

        /*
        $groupFilter = new Filter();
        foreach ((new GroupMembership())->getGroupIdList() as $groupId) {
            $groupFilter->orEqual($reader->model->groupId,$groupId);
        }
        $groupFilter->orIsNull($reader->model->groupId);*/

        $reader->filter->andFilter((new GroupMembership())->getGroupFilter($reader->model->groupId));

        $reader->addOrder($reader->model->date);
        //$reader->paginationLimit = ProcessConfig::PAGINATION_LIMIT;

        $table = new AdminClickableTable($this);

        //$div = new Div($page);

        $header = new TableHeader($table);
        $header->addText($reader->model->date->label);
        $header->addText($reader->model->title->label);
        /*$header->addText('View');
        $header->addText('Type');
        $header->addText('Source');*/
        $header->addText('Group');
        $header->addText('Source Type');

        foreach ($reader->getData() as $calendarIndexRow) {

            $row = new BootstrapClickableTableRow($table);
            $row->addText($calendarIndexRow->date->getShortDateLeadingZeroFormat());
            $row->addText($calendarIndexRow->title);
            $row->addText($calendarIndexRow->group->group);

            $row->addText($calendarIndexRow->content->contentType->contentType);

            /*
            $type = $calendarIndexRow->content->getContentType();
            $type->getView($row);

            $row->addText($type->typeLabel);

            $row->addClickableSite($type->getViewSite());*/


            $site= clone($this->redirectSite);  // clone(CalendarSite::$site);
            $site->addParameter(new ContentParameter($calendarIndexRow->contentId));  // CalendarParameter($calendarIndexRow->id));
            $row->addClickableSite($site);

        }

        $pagination = new BootstrapPagination($this);
        $pagination->paginationReader = $reader;





        /*
        $reader = new CalendarIndexPaginationReader();
        $reader->model->loadContent();
        $reader->model->content->loadContentType();

        $reader->filter->andEqualOrGreater($reader->model->date, (new Date())->setNow()->getIsoDateFormat());

        $reader->addOrder($reader->model->date);
        $reader->paginationLimit = ProcessConfig::PAGINATION_LIMIT;

        $table = new AdminClickableTable($page);

        $div = new Div($page);

        $header = new TableHeader($table);
        $header->addText($reader->model->date->label);
        $header->addText($reader->model->title->label);
        $header->addText('View');
        $header->addText('Type');
        $header->addText('Source');
        $header->addText('Source Type');

        foreach ($reader->getData() as $calendarIndexRow) {

            $row = new BootstrapClickableTableRow($table);
            $row->addText($calendarIndexRow->date->getShortDateLeadingZeroFormat());
            $row->addText($calendarIndexRow->title);


            $row->addText($calendarIndexRow->content->contentType->contentType);

            $type = $calendarIndexRow->content->getContentType();
            $type->getView($row);

            $row->addText($type->typeLabel);

            $row->addClickableSite($type->getViewSite());

        }


        $pagination = new BootstrapPagination($page);
        $pagination->paginationReader = $reader;*/



        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}