<?php

namespace Nemundo\Package\Bootstrap\Helper\Ratio;


use Nemundo\Html\Block\Div;

class BootstrapRatioDiv extends Div
{

    public $aspectRatio = BootstrapAspectRatio::RATIO_4_3;

    public function getContent()
    {

        $this->addCssClass('ratio');
        $this->addCssClass($this->aspectRatio);

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}