<?php

namespace Nemundo\Content\App\Camera\Com\Redefine;



use Nemundo\Admin\Com\Redefine\AbstractAdminSearchRedefine;

class YearRedefine extends AbstractAdminSearchRedefine
{

    public function getContent()
    {
        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}