<?php


namespace Nemundo\Admin\Com\Player;


use Nemundo\Html\Player\VideoPlayer;

class AdminVideoPlayer extends VideoPlayer
{

    public function getContent()
    {

        $this->addCssClass('mw-100');

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}