<?php


namespace Nemundo\Content\App\Explorer\Content\Container;


use Nemundo\Content\App\Explorer\Data\ContainerRename\ContainerRename;
use Nemundo\Content\App\Explorer\Data\ContainerRename\ContainerRenameReader;
use Nemundo\Content\Index\Log\Type\AbstractLogContentType;

class ContainerRenameLogContentType extends AbstractLogContentType
{

    public $containerOld;

    public $containerNew;


    protected function loadContentType()
    {
        $this->typeLabel='Container Rename';
     $this->typeId='4c54877f-e034-4a19-b393-66ca8ad5db19';
    }

    protected function onCreate()
    {

        //parent::onCreate(); // TODO: Change the autogenerated stub


        $data=new ContainerRename();
        $data->containerOld=$this->containerOld;
        $data->containerNew=$this->containerNew;
      $this->dataId=  $data->save();



    }


    public function getSubject()
    {

        $subject= 'Rename to '.(new ContainerRenameReader())->getRowById($this->dataId)->containerNew;
        return $subject;

     //   return parent::getSubject(); // TODO: Change the autogenerated stub
    }


}