<?php


namespace Nemundo\Content\App\File\Content\Upload;


use Nemundo\Content\App\File\Com\Form\UrlDownloadForm;
use Nemundo\Content\App\File\Job\UrlDownloadJob;
use Nemundo\Content\Form\AbstractContentContainer;

class UrlDownloadJobContentForm extends AbstractContentContainer
{

    public $formName='Url Download (Background) Job';


    public function getContent()
    {


        new UrlDownloadForm($this);

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


}