<?php

namespace Nemundo\Content\Com\Form;


use Nemundo\Content\Com\ListBox\ContentTypeListBox;
use Nemundo\Content\Data\ContentTypeCollectionContentType\ContentTypeCollectionContentType;
use Nemundo\Package\Bootstrap\Form\BootstrapForm;

class ContentTypeCollectionAddForm extends BootstrapForm
{


    public $collectionId;


    /**
     * @var ContentTypeListBox
     */
    private $contentType;

    public function getContent()
    {

        $this->contentType=new ContentTypeListBox($this);
        $this->contentType->validation=true;

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {

        $data=new ContentTypeCollectionContentType();
        $data->collectionId=$this->collectionId;
        $data->contentTypeId=$this->contentType->getValue();
        $data->save();


    }

}