<?php


namespace Nemundo\Content\App\Project\Content\ProjectPhase;


use Nemundo\Content\Index\Tree\Type\AbstractParentContentListing;

class ProjectPhaseParentContentList extends AbstractParentContentListing
{

    public function getContent()
    {

        // Index


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}